source 'http://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'capybara'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'pry'
gem 'allure-cucumber'
gem 'allure-rspec'
gem 'httparty'
gem 'json'
gem 'json_pure'