email:
  - email_1: teste_autimacaaooo@gmail.com
    email_existente: teste_qa@gmail.com
    login: user_qa@teste.com
    vazio:

password:
  - pass1: user123
    vazio:

transacao:
  - data: '20220503'
    valor: 501.56
    vazio:

valor:
  - valor0: 501.56
    valor1: